"""add is_admin field to users table

Revision ID: 004
Revises: 003
Create Date: 2025-08-25 15:35:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET is_admin = false WHERE is_admin IS NULL")
    # Make the column non-nullable with default False
    op.alter_column('users', 'is_admin', nullable=False, server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
